version: 0.0
os: ubuntu
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /var/www/html
    owner: ubuntu
    group: ubuntu
  AfterInstall:
    - location: script/AfterInstall.sh
      runas: root
  ApplicationStart:
    - location: script/ApplicationStart.sh
      runas: root
