version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/codedeploy
hooks:
AfterInstall:
    - location: script/update_permissions.sh
      runas: ubuntu
    - location: script/afterinstall.sh
      runas: ubuntu
