version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: script/AfterInstall.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: script/ApplicationStart.sh
      timeout: 300
      runas: ubuntu
